# Generated by Django 4.1 on 2022-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_rename_marks_studentdetails_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='user_image',
            field=models.ImageField(default=1, upload_to='picture'),
            preserve_default=False,
        ),
    ]
