# Generated by Django 4.1 on 2022-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_studentdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='user_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
