# Generated by Django 4.1 on 2022-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_alter_studentdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='user_image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
